<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260121174004 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE achievements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT NOT NULL, icon VARCHAR(255) DEFAULT NULL, points_required INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE activity_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(100) NOT NULL, details JSON DEFAULT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_activity_user ON activity_logs (user_id)');
        $this->addSql('CREATE INDEX idx_activity_action ON activity_logs (action)');
        $this->addSql('CREATE INDEX idx_activity_created ON activity_logs (created_at)');
        $this->addSql('CREATE TABLE challenges (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, duration_days INT NOT NULL, difficulty_level VARCHAR(20) NOT NULL, points INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE quotes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, author VARCHAR(255) DEFAULT NULL, category VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE user_achievements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, earned_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, achievement_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_51EE02FCA76ED395 ON user_achievements (user_id)');
        $this->addSql('CREATE INDEX IDX_51EE02FCB3EC99FE ON user_achievements (achievement_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_achievement ON user_achievements (user_id, achievement_id)');
        $this->addSql('CREATE TABLE user_challenges (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(20) NOT NULL, progress INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, challenge_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A0D2610CA76ED395 ON user_challenges (user_id)');
        $this->addSql('CREATE INDEX IDX_A0D2610C98A21AC6 ON user_challenges (challenge_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_challenge ON user_challenges (user_id, challenge_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE activity_logs ADD CONSTRAINT FK_F34B1DCEA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_achievements ADD CONSTRAINT FK_51EE02FCA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_achievements ADD CONSTRAINT FK_51EE02FCB3EC99FE FOREIGN KEY (achievement_id) REFERENCES achievements (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_challenges ADD CONSTRAINT FK_A0D2610CA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_challenges ADD CONSTRAINT FK_A0D2610C98A21AC6 FOREIGN KEY (challenge_id) REFERENCES challenges (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity_logs DROP CONSTRAINT FK_F34B1DCEA76ED395');
        $this->addSql('ALTER TABLE user_achievements DROP CONSTRAINT FK_51EE02FCA76ED395');
        $this->addSql('ALTER TABLE user_achievements DROP CONSTRAINT FK_51EE02FCB3EC99FE');
        $this->addSql('ALTER TABLE user_challenges DROP CONSTRAINT FK_A0D2610CA76ED395');
        $this->addSql('ALTER TABLE user_challenges DROP CONSTRAINT FK_A0D2610C98A21AC6');
        $this->addSql('DROP TABLE achievements');
        $this->addSql('DROP TABLE activity_logs');
        $this->addSql('DROP TABLE challenges');
        $this->addSql('DROP TABLE quotes');
        $this->addSql('DROP TABLE user_achievements');
        $this->addSql('DROP TABLE user_challenges');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
