# ===============================================
# 🌐 Nginx Dockerfile
# ===============================================

FROM nginx:alpine

# Kopiowanie konfiguracji
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf

WORKDIR /var/www/html
